Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1617, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
