Traceback (most recent call last):
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
Traceback (most recent call last):
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
Traceback (most recent call last):
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
  File "clusterSweep.py", line 82, in <module>
  File "clusterSweep.py", line 82, in <module>
ValueError: max() arg is an empty sequence
    fig1, ax1 = plotter.plotVarianceAndError()
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
Traceback (most recent call last):
ValueError: max() arg is an empty sequence
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
srun: error: enc1-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
srun: error: enc1-node11: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node6: task 0: Exited with exit code 1
srun: error: enc1-node6: task 0: Exited with exit code 1
srun: error: enc1-node6: task 0: Exited with exit code 1
srun: error: enc1-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
srun: error: enc1-node8: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node5: task 0: Exited with exit code 1
srun: error: enc1-node5: task 0: Exited with exit code 1
srun: error: enc1-node5: task 0: Exited with exit code 1
srun: error: enc1-node5: task 0: Exited with exit code 1
srun: error: enc1-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node7: task 0: Exited with exit code 1
srun: error: enc1-node7: task 0: Exited with exit code 1
srun: error: enc1-node7: task 0: Exited with exit code 1
srun: error: enc1-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node9: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
srun: error: enc1-node10: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node7: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc0-node6: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "clusterSweep.py", line 82, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1618, in plotVarianceAndError
    ax[0].set_ylim(bottom=0,top=max(W_snr)+0.15)
ValueError: max() arg is an empty sequence
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
